#!/usr/bin/env python3
"""vendored-skill-integrity.py -- does each vendored skill still match the commit it CLAIMS?

WHY THIS EXISTS (card 3c73a420, Cybersec 2026-09-13)
  Every vendored skill dir carries a VENDORED.md that says "do not edit here" and names an
  upstream commit. Nothing ever checked that claim: a grep for VENDORED.md across store/,
  scripts/ and src/ returned exactly ONE file -- vendor-skill.sh, the WRITER. There was no
  reader. The registry's whole supply-chain control watches the UPSTREAM door (detect + flag,
  never auto-apply) and left the LOCAL door unwatched.

  First run of this check: 31 vendored dirs, 13 matched, 18 differed, 0 unverifiable. Every
  one of the 18 was explainable (documented Peti exclusions, generated bytecode, deliberate
  fleet adaptations of SKILL.md). So this is not a tamper detector that found a tamper -- it
  is the baseline that makes a future tamper VISIBLE, because today an unauthorised edit would
  be indistinguishable from the 18 sanctioned ones.

METHOD
  Reconstruct the upstream payload with `git archive <sha> [subdir]` from the watch clone
  recorded in VENDORED.md, then diff it by CONTENT HASH against the live directory. Compare
  the resulting delta set against the sanctioned baseline; complain only about deltas that
  are NOT in the baseline.

THREE DESIGN RULES, each bought with a past fleet incident:

  1. FAIL-CLOSED ON UNVERIFIABLE. A missing watch clone or a failing `git archive` is a
     FAILURE, never a silent skip. The registry already demonstrated the opposite failure
     mode: two type=code entries point `vendored_to` at paths that do not exist, so their
     drift review inspects an empty path and reports nothing wrong. "I could not check" is
     not "I checked and it is fine".

  2. THE VERDICT MUST BE PROVABLE IN BOTH DIRECTIONS. --selftest runs a real PASS case and a
     real FAIL case against throwaway git fixtures. A guard only ever exercised on its failing
     input can be silently broken for the passing one, and then it approves everything.

  3. NO PATTERN-EXCLUSION THAT AN ATTACKER CAN STAND IN. __pycache__ is excluded from the
     verdict (its contents churn with every interpreter change, and an attacker who can write
     a .pyc can already write the .py next to it, so it grants no new power) -- BUT an ORPHAN
     .pyc, one with no matching source file, is a hard FAIL. That is the classic hide-the-
     source trick, and it is exactly the case the exclusion would otherwise cover.

Exit: 0 = no unsanctioned delta | 1 = unsanctioned delta or unverifiable | 2 = bad usage
"""
import argparse
import hashlib
import io
import json
import os
import re
import subprocess
import sys
import tarfile

# vendor-skill.sh writes these two itself; they are ours, never upstream's.
OURS = {"VENDORED.md", "UPSTREAM-LICENSE"}
DEFAULT_BASELINE = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "vendored-skill-sanctioned.json")


def skill_roots(home):
    """Global skills dir plus every agent-local one. An agent-local copy is NOT a mirror:
    it shadows the global skill for that agent, and two of the registry's own type=code
    entries live ONLY in agent-local dirs, with nothing at the global path they name."""
    roots = []
    g = os.path.join(home, ".claude", "skills")
    if os.path.isdir(g):
        roots.append(g)
    agents = os.path.join(home, "marveen", "agents")
    if os.path.isdir(agents):
        for a in sorted(os.listdir(agents)):
            p = os.path.join(agents, a, ".claude", "skills")
            if os.path.isdir(p):
                roots.append(p)
    return roots


def parse_vendored_md(path):
    text = open(path, encoding="utf-8", errors="replace").read()

    def row(key):
        m = re.search(r"^\|\s*%s\s*\|\s*(.+?)\s*\|\s*$" % re.escape(key), text, re.M)
        return m.group(1).strip() if m else None

    sha = (row("vendored commit") or "").strip("`").strip()
    subdir = row("subdir") or ""
    if subdir == "<repo root>":
        subdir = ""
    return {"sha": sha, "subdir": subdir, "clone": row("watch clone"), "repo": row("source repo")}


def upstream_hashes(clone, sha, subdir):
    """Payload at <sha> as {relpath: sha256}. Returns (None, reason) when it cannot be built --
    the caller MUST treat that as a failure, not as an empty diff."""
    cmd = ["git", "-C", clone, "archive", sha]
    if subdir:
        cmd.append(subdir)
    proc = subprocess.run(cmd, capture_output=True)
    if proc.returncode != 0:
        return None, (proc.stderr.decode("utf-8", "replace").strip().splitlines() or ["git archive failed"])[0]
    out = {}
    try:
        with tarfile.open(fileobj=io.BytesIO(proc.stdout)) as tf:
            for member in tf.getmembers():
                if not member.isfile():
                    continue
                name = member.name
                if subdir and name.startswith(subdir + "/"):
                    name = name[len(subdir) + 1:]
                fh = tf.extractfile(member)
                out[name] = hashlib.sha256(fh.read()).hexdigest()
    except tarfile.TarError as exc:
        return None, "unreadable archive: %s" % exc
    return out, None


def live_hashes(directory):
    """Live payload as {relpath: sha256}, skipping .git and our own two files.

    A symlink is recorded as its TARGET, never followed: following it would let a link
    planted inside a vendored skill make an out-of-tree file look like upstream content."""
    out = {}
    for root, dirs, files in os.walk(directory):
        dirs[:] = [d for d in dirs if d != ".git"]
        for fn in files:
            full = os.path.join(root, fn)
            rel = os.path.relpath(full, directory)
            if rel in OURS:
                continue
            if os.path.islink(full):
                out[rel] = "symlink:" + os.readlink(full)
                continue
            try:
                with open(full, "rb") as fh:
                    out[rel] = hashlib.sha256(fh.read()).hexdigest()
            except OSError as exc:
                out[rel] = "unreadable:%s" % exc
    return out


def is_pycache(rel):
    return "__pycache__" in rel.replace("\\", "/").split("/")


def orphan_pyc(rel, live):
    """A .pyc whose source is absent. CPython validates a .pyc against its .py, so bytecode
    beside its source grants an attacker nothing they did not already have -- bytecode with
    NO source is the hide-the-source trick, and must not ride the __pycache__ exclusion."""
    parts = rel.replace("\\", "/").split("/")
    if not parts[-1].endswith(".pyc"):
        return False
    stem = parts[-1].split(".")[0]
    parent = "/".join(parts[:-2])  # strip filename and the __pycache__ segment
    candidate = (parent + "/" if parent else "") + stem + ".py"
    return candidate not in live


def git_state(directory):
    """A vendored copy that is itself a git working tree is a standing bypass of the
    'never auto-apply' rule: one `git pull` applies upstream fleet-wide, and one
    `git restore .` undoes every deliberate exclusion held as a tracked deletion."""
    if not os.path.isdir(os.path.join(directory, ".git")):
        return None
    def git(*args):
        p = subprocess.run(("git", "-C", directory) + args, capture_output=True, text=True)
        # rstrip ONLY: `git status --porcelain` encodes state in columns 1-2, so a leading
        # space is DATA. A .strip() here ate the first line's leading space and undercounted
        # the deletions by exactly one -- measured on caveman, 9 reported for 10 real.
        return p.stdout.rstrip("\n") if p.returncode == 0 else ""
    branch = git("rev-parse", "--abbrev-ref", "HEAD").strip()
    tracking = git("rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{upstream}").strip()
    deleted = [l[3:] for l in git("status", "--porcelain").splitlines() if l[:2] in (" D", "D ")]
    return {"branch": branch, "tracking": tracking,
            "tracked_deletions": len(deleted), "deleted_paths": deleted}


def inspect(directory, meta):
    """One skill -> its finding dict. 'ok' False means the run must fail."""
    res = {"dir": directory, "sha": meta["sha"], "subdir": meta["subdir"],
           "git": git_state(directory), "ok": True, "unverifiable": None,
           "missing": [], "extra": [], "changed": [], "generated": 0, "orphan_pyc": [],
           "hashes": {}}

    clone = meta["clone"]
    if not meta["sha"] or not clone:
        res["ok"] = False
        res["unverifiable"] = "VENDORED.md names no commit or no watch clone"
        return res
    if not os.path.isdir(clone):
        res["ok"] = False
        res["unverifiable"] = "watch clone missing: %s" % clone
        return res

    upstream, err = upstream_hashes(clone, meta["sha"], meta["subdir"])
    if upstream is None:
        res["ok"] = False
        res["unverifiable"] = err
        return res

    live = live_hashes(directory)
    for rel in sorted(set(upstream) - set(live)):
        res["missing"].append(rel)
    for rel in sorted(set(live) - set(upstream)):
        if is_pycache(rel):
            res["generated"] += 1
            if orphan_pyc(rel, live):
                res["orphan_pyc"].append(rel)
            continue
        res["extra"].append(rel)
        res["hashes"][rel] = live[rel]
    for rel in sorted(set(upstream) & set(live)):
        if upstream[rel] != live[rel]:
            res["changed"].append(rel)
            res["hashes"][rel] = live[rel]
    return res


def delta_keys(res):
    """Stable identity of each delta, for matching against the sanctioned baseline.

    A present-file delta carries its CONTENT HASH, never the path alone. Sanctioning
    "changed:SKILL.md" by path would pin the PROXY (that the file differs) instead of the
    OUTCOME (what it differs to), and every later edit of that same file would inherit the
    blessing. Measured while building this: with path-only keys, appending a line to an
    already-sanctioned SKILL.md left the run green -- the guard was blind on exactly the
    file most worth watching, because being edited once is what earned it the exemption.
    'missing' keeps the path alone: an absent file has no content to bind to."""
    return (["missing:" + r for r in res["missing"]]
            + ["extra:" + r + "@" + res["hashes"].get(r, "?") for r in res["extra"]]
            + ["changed:" + r + "@" + res["hashes"].get(r, "?") for r in res["changed"]]
            + ["orphan-pyc:" + r for r in res["orphan_pyc"]])


def load_baseline(path):
    if not os.path.isfile(path):
        return {}
    with open(path, encoding="utf-8") as fh:
        return json.load(fh).get("sanctioned", {})


def main():
    ap = argparse.ArgumentParser(description="Verify vendored skills against the commit they claim.")
    ap.add_argument("--home", default=os.path.expanduser("~"))
    ap.add_argument("--baseline", default=DEFAULT_BASELINE)
    ap.add_argument("--record", action="store_true",
                    help="write today's deltas as the sanctioned baseline (a deliberate act)")
    ap.add_argument("--quiet", action="store_true", help="print only unsanctioned findings")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()

    if args.selftest:
        return selftest()

    baseline = load_baseline(args.baseline)
    results, recorded = [], {}
    for root in skill_roots(args.home):
        for name in sorted(os.listdir(root)):
            d = os.path.join(root, name)
            md = os.path.join(d, "VENDORED.md")
            if os.path.isfile(md):
                results.append(inspect(d, parse_vendored_md(md)))

    failures = 0
    for res in results:
        key = res["dir"].replace(args.home, "~")
        keys = delta_keys(res)
        recorded[key] = sorted(keys)
        sanctioned = set(baseline.get(key, []))
        new = [k for k in keys if k not in sanctioned]
        # An orphan .pyc is never sanctionable: it is the one case the __pycache__
        # exclusion would otherwise swallow, so a baseline entry must not license it.
        new += [k for k in keys if k.startswith("orphan-pyc:") and k in sanctioned]
        bad = res["unverifiable"] or new
        if bad:
            failures += 1
        elif args.quiet:
            continue
        print("=" * 76)
        print("%s\n  commit %s  subdir=%s" % (key, res["sha"][:12], res["subdir"] or "<root>"))
        if res["git"]:
            g = res["git"]
            print("  GIT WORKING TREE: branch=%s tracking=%s tracked-deletions=%d"
                  % (g["branch"] or "?", g["tracking"] or "(none)", g["tracked_deletions"]))
        if res["unverifiable"]:
            print("  UNVERIFIABLE: %s" % res["unverifiable"])
        elif new:
            print("  UNSANCTIONED DELTA (%d):" % len(new))
            for k in new[:12]:
                print("    %s" % k)
            if len(new) > 12:
                print("    ... +%d more" % (len(new) - 12))
        else:
            extra = " (%d sanctioned)" % len(keys) if keys else ""
            print("  OK%s%s" % (extra, ", %d generated" % res["generated"] if res["generated"] else ""))

    if args.record:
        with open(args.baseline, "w", encoding="utf-8") as fh:
            json.dump({"note": "Sanctioned vendored-skill deltas. Each entry is a DECISION: "
                               "the delta is known and accepted. Re-record deliberately.",
                       "sanctioned": recorded}, fh, indent=2, sort_keys=True)
            fh.write("\n")
        print("\nbaseline written: %s (%d dirs)" % (args.baseline, len(recorded)))
        return 0

    print("=" * 76)
    print("vendored dirs: %d | clean or sanctioned: %d | needing attention: %d"
          % (len(results), len(results) - failures, failures))
    return 1 if failures else 0


def selftest():
    """Both directions on real fixtures: a clean tree must PASS, a tampered one must FAIL."""
    import shutil
    import tempfile

    fails = []

    def check(label, want, got):
        if got != want:
            fails.append("%s: want=%r got=%r" % (label, want, got))

    tmp = tempfile.mkdtemp(prefix="vsi-selftest-")
    try:
        clone = os.path.join(tmp, "clone")
        os.makedirs(os.path.join(clone, "skills", "demo"))
        with open(os.path.join(clone, "skills", "demo", "SKILL.md"), "w") as fh:
            fh.write("upstream body\n")
        subprocess.run(["git", "init", "-q", clone], check=True)
        subprocess.run(["git", "-C", clone, "config", "user.email", "t@t"], check=True)
        subprocess.run(["git", "-C", clone, "config", "user.name", "t"], check=True)
        subprocess.run(["git", "-C", clone, "add", "-A"], check=True)
        subprocess.run(["git", "-C", clone, "commit", "-qm", "seed"], check=True)
        sha = subprocess.run(["git", "-C", clone, "rev-parse", "HEAD"],
                             capture_output=True, text=True, check=True).stdout.strip()

        def make_live(name):
            d = os.path.join(tmp, name)
            os.makedirs(d, exist_ok=True)
            shutil.copy(os.path.join(clone, "skills", "demo", "SKILL.md"), os.path.join(d, "SKILL.md"))
            with open(os.path.join(d, "VENDORED.md"), "w") as fh:
                fh.write("| vendored commit | `%s` |\n| subdir | skills/demo |\n"
                         "| watch clone | %s |\n| source repo | x |\n" % (sha, clone))
            return d

        # 1. THE PASS CASE. Without this the guard could be broken in the approving direction
        #    and nobody would notice, because a guard that always fails still "works" on its
        #    failing input.
        clean = make_live("clean")
        res = inspect(clean, parse_vendored_md(os.path.join(clean, "VENDORED.md")))
        check("an untouched copy verifies clean", ([], [], [], None),
              (res["missing"], res["extra"], res["changed"], res["unverifiable"]))

        # 2. An edited file is detected by CONTENT, not by name or size.
        edited = make_live("edited")
        with open(os.path.join(edited, "SKILL.md"), "w") as fh:
            fh.write("tampered body\n")   # same name, same length class
        res = inspect(edited, parse_vendored_md(os.path.join(edited, "VENDORED.md")))
        check("an edited file is reported as changed", ["SKILL.md"], res["changed"])

        # 3. An ADDED file is a delta too: injection does not need to edit anything.
        added = make_live("added")
        with open(os.path.join(added, "EXTRA.md"), "w") as fh:
            fh.write("injected\n")
        res = inspect(added, parse_vendored_md(os.path.join(added, "VENDORED.md")))
        check("an added file is reported as extra", ["EXTRA.md"], res["extra"])

        # 4. FAIL-CLOSED: a missing watch clone must fail, never read as "no differences".
        gone = make_live("gone")
        with open(os.path.join(gone, "VENDORED.md"), "w") as fh:
            fh.write("| vendored commit | `%s` |\n| subdir | skills/demo |\n"
                     "| watch clone | %s/nope |\n| source repo | x |\n" % (sha, tmp))
        res = inspect(gone, parse_vendored_md(os.path.join(gone, "VENDORED.md")))
        check("a missing watch clone fails closed", (False, True),
              (res["ok"], bool(res["unverifiable"])))

        # 5. Generated bytecode beside its source is noise, not a finding.
        pyc = make_live("pyc")
        os.makedirs(os.path.join(pyc, "__pycache__"))
        with open(os.path.join(pyc, "mod.py"), "w") as fh:
            fh.write("x = 1\n")
        with open(os.path.join(pyc, "__pycache__", "mod.cpython-314.pyc"), "wb") as fh:
            fh.write(b"\x00bytecode")
        res = inspect(pyc, parse_vendored_md(os.path.join(pyc, "VENDORED.md")))
        check("bytecode beside its source is not a delta", (["mod.py"], 1, []),
              (res["extra"], res["generated"], res["orphan_pyc"]))

        # 6. THE DOOR IN RULE 3: bytecode with NO source rides the exclusion unless caught.
        orphan = make_live("orphan")
        os.makedirs(os.path.join(orphan, "__pycache__"))
        with open(os.path.join(orphan, "__pycache__", "ghost.cpython-314.pyc"), "wb") as fh:
            fh.write(b"\x00bytecode")
        res = inspect(orphan, parse_vendored_md(os.path.join(orphan, "VENDORED.md")))
        check("orphan bytecode is caught despite the exclusion",
              ["__pycache__/ghost.cpython-314.pyc"], res["orphan_pyc"])

        # 8. THE GUARD'S OWN FOUNDING FAILURE. Sanctioning a delta by PATH blesses the file,
        #    not the content: once "changed:SKILL.md" is accepted, every later edit of that
        #    file inherits the exemption. Caught on the live fleet -- an injected line into an
        #    already-sanctioned SKILL.md left the run green. The key must carry the hash.
        drift = make_live("drift")
        with open(os.path.join(drift, "SKILL.md"), "w") as fh:
            fh.write("adapted body\n")
        meta = parse_vendored_md(os.path.join(drift, "VENDORED.md"))
        sanctioned = set(delta_keys(inspect(drift, meta)))
        with open(os.path.join(drift, "SKILL.md"), "a") as fh:
            fh.write("<!-- injected later -->\n")
        after = delta_keys(inspect(drift, meta))
        check("a second edit of a sanctioned file is NOT covered by it",
              True, any(k not in sanctioned for k in after))

        # 8. THE OFF-BY-ONE THIS FILE WAS WRITTEN WITH. `git status --porcelain` encodes state
        #    in columns 1-2, so the leading space is data; stripping it made the FIRST deleted
        #    file invisible and reported 9 deletions for 10. Two deletions, so a fix that only
        #    shifts the error cannot pass.
        with open(os.path.join(clone, "skills", "demo", "second.md"), "w") as fh:
            fh.write("two\n")
        subprocess.run(["git", "-C", clone, "add", "-A"], check=True)
        subprocess.run(["git", "-C", clone, "commit", "-qm", "second"], check=True)
        wt = os.path.join(tmp, "wt")
        subprocess.run(["git", "clone", "-q", clone, wt], check=True)
        os.remove(os.path.join(wt, "skills", "demo", "SKILL.md"))
        os.remove(os.path.join(wt, "skills", "demo", "second.md"))
        # Assert the PATHS, not just the count: a .strip() here does not merely miscount,
        # it EATS the first line's leading space and then l[3:] slices one char into the path
        # ("kills/demo/..."). A count-only assertion can be satisfied by a filter that is
        # loose enough to re-admit the mangled line, which is exactly what happened here.
        check("porcelain leading space is data, not padding",
              ["skills/demo/SKILL.md", "skills/demo/second.md"],
              sorted(git_state(wt)["deleted_paths"]))

        # 7. A symlink is recorded by TARGET, not followed -- otherwise a planted link makes
        #    an out-of-tree file read as upstream content.
        link = make_live("link")
        os.remove(os.path.join(link, "SKILL.md"))
        os.symlink("/etc/hostname", os.path.join(link, "SKILL.md"))
        res = inspect(link, parse_vendored_md(os.path.join(link, "VENDORED.md")))
        check("a symlink swap is reported as changed", ["SKILL.md"], res["changed"])
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    for f in fails:
        print("FAIL: %s" % f)
    print("selftest: %d checks, %d failed" % (9, len(fails)))
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
