#!/bin/bash
# Install the Windows-side WSL watchdog: the OUTER resilience net.
#
# The three in-WSL systemd guards recover component-level wedges (deaf channel,
# stuck modal, full disk) but they cannot recover a TOTAL WSL/systemd wedge --
# if the whole VM hangs, nothing inside it runs. This installs a Windows
# Scheduled Task that probes MikroB liveness from OUTSIDE the VM and, only after
# a SUSTAINED wedge, restarts the WSL distro (the boot autostart + systemd/linger
# bring MikroB back). High threshold + dual-signal probe so a healthy fleet is
# never nuked over a transient blip.
#
# WSL-only + idempotent. Safe to re-run (install-linux.sh / startup.sh call it).
# Non-WSL hosts and hosts without powershell.exe are a silent no-op.
set -euo pipefail

INSTALL_DIR="$(cd "$(dirname "$0")/.." && pwd)"

# --- guard: WSL only ---
if ! grep -qi microsoft /proc/version 2>/dev/null; then
  echo "not WSL -- Windows watchdog not applicable; no-op."
  exit 0
fi
PS="$(command -v powershell.exe || true)"
[ -z "$PS" ] && PS="/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe"
if [ ! -x "$PS" ]; then
  echo "powershell.exe not reachable -- cannot install Windows watchdog; no-op."
  exit 0
fi
WSLEXE="/mnt/c/Windows/System32/wsl.exe"

WSL_USER="$(id -un)"

# --- resolve the distro name (this VM) ---
DISTRO="${WSL_DISTRO_NAME:-}"
if [ -z "$DISTRO" ]; then
  # Parse `wsl.exe -l -v`: prefer the default (*) row, else the first Running row.
  DISTRO="$("$WSLEXE" -l -v 2>/dev/null | tr -d '\0\r' | awk '/\*/{print $2; found=1} END{if(!found) print ""}')"
fi
[ -z "$DISTRO" ] && DISTRO="Ubuntu"

# --- Windows target dir (LOCALAPPDATA\MikroB), both Windows + WSL views ---
WIN_LOCALAPPDATA="$("$PS" -NoProfile -Command '$env:LOCALAPPDATA' 2>/dev/null | tr -d '\r')"
[ -z "$WIN_LOCALAPPDATA" ] && { echo "could not resolve LOCALAPPDATA; abort"; exit 1; }
WIN_DIR="${WIN_LOCALAPPDATA}\\MikroB"
WSL_DIR="$(wslpath -u "$WIN_LOCALAPPDATA")/MikroB"
mkdir -p "$WSL_DIR"

WATCHDOG_WIN="${WIN_DIR}\\mikrob-wsl-watchdog.ps1"
WATCHDOG_WSL="${WSL_DIR}/mikrob-wsl-watchdog.ps1"
TASK_NAME="MikroB-WSL-Watchdog"
SCHTASKS="/mnt/c/Windows/System32/schtasks.exe"

# ----------------------------------------------------------------------------
# 1) The watchdog PS1. Probes liveness via the in-WSL probe script; on a
#    sustained wedge (MAX_FAILS consecutive) restarts the distro.
# ----------------------------------------------------------------------------
cat > "$WATCHDOG_WSL" <<PS1EOF
# MikroB WSL watchdog -- outer net for a TOTAL WSL/VM wedge. Auto-generated by
# scripts/install-wsl-watchdog.sh; edit the generator, not this copy.
\$Distro   = "$DISTRO"
\$WslUser  = "$WSL_USER"
\$Probe    = "$INSTALL_DIR/scripts/wsl-liveness-probe.sh"
\$MaxFails = 3          # consecutive fails (~15 min @ 5-min cadence) before restart
\$StateDir = "\$env:LOCALAPPDATA\\MikroB"
\$StateFile = "\$StateDir\\wsl-watchdog-fails.txt"
\$LogFile  = "\$StateDir\\wsl-watchdog.log"
New-Item -ItemType Directory -Force -Path \$StateDir | Out-Null
function Log(\$m){ "\$(Get-Date -Format o) \$m" | Out-File -Append -Encoding utf8 \$LogFile }

# Probe INSIDE wsl. If the VM/systemd is wedged, wsl.exe can't run it and
# \$LASTEXITCODE != 0 -> that IS the total-wedge signal.
\$out = & wsl.exe -d \$Distro -u \$WslUser -- \$Probe 2>\$null
\$healthy = (\$LASTEXITCODE -eq 0) -and (\$out -match "OK")

if (\$healthy) { Set-Content -Path \$StateFile -Value "0"; exit 0 }

\$fails = 0
if (Test-Path \$StateFile) { \$fails = [int](Get-Content \$StateFile -ErrorAction SilentlyContinue) }
\$fails++
Set-Content -Path \$StateFile -Value "\$fails"
Log "probe unhealthy (out='\$out' exit=\$LASTEXITCODE) -- consecutive fails=\$fails/\$MaxFails"

if (\$fails -ge \$MaxFails) {
  Log "RESTARTING WSL distro \$Distro (sustained wedge)"
  & wsl.exe --terminate \$Distro 2>\$null
  Start-Sleep -Seconds 5
  & wsl.exe -d \$Distro --exec /bin/true 2>\$null   # re-launch; systemd+linger revive MikroB
  Set-Content -Path \$StateFile -Value "0"
  Log "WSL restart issued"
}
exit 0
PS1EOF

echo "Rendered Windows watchdog for distro=$DISTRO user=$WSL_USER -> $WIN_DIR"

# ----------------------------------------------------------------------------
# 2) Register the Scheduled Task via schtasks.exe. Runs every 5 min as the
#    interactive user (matches the working MikroB Autostart pattern, reliable
#    wsl.exe control). Notes: (a) schtasks is used instead of PowerShell's
#    Register-ScheduledTask because the latter's RepetitionDuration=MaxValue
#    emits out-of-range TaskXML that Task Scheduler rejects; (b) NO /RL HIGHEST
#    -- elevation would need an admin shell (Access Denied otherwise) and the
#    watchdog only needs to call wsl.exe, not admin rights; (c) the .ps1 path
#    lives under AppData\Local\MikroB (no spaces) so /TR needs no inner quotes.
#    /F overwrites, so re-running is idempotent.
# ----------------------------------------------------------------------------
TR="powershell -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File ${WATCHDOG_WIN}"
if "$SCHTASKS" /Create /TN "$TASK_NAME" /TR "$TR" /SC MINUTE /MO 5 /F >/dev/null 2>&1; then
  echo "Scheduled Task '$TASK_NAME' registered (every 5 min, as $WSL_USER)."
else
  echo "warn: schtasks registration failed. Register manually in a cmd/PowerShell:"
  echo "  schtasks /Create /TN \"$TASK_NAME\" /TR \"$TR\" /SC MINUTE /MO 5 /F"
fi
